### ISSUE TITLE
selectWindow selenese command

### ISSUE THREAD

**Issue by richi235** [teodesian/Selenium-Remote-Driver#274]
Selenium IDE 2.9.1 seems to include a `selectWindow` command. 
This makes it possible to record and replay operations in javascript alerts or the download window.

When I export an test case containing this command to perl5 (using the js plugin from this repo), 
I get a script with all xpaths correct (already a great amount of work reduced, thanks) but it also says: 

```
# ERROR: Caught exception [ERROR: Unsupported command [selectWindow | name=rbfui-0.24302320467994165 | ]]
```

Is there a workaround? Are there plans to support selectWindow in the future?

**Comment by gempesaw** [comment]
Honestly, I'm surprised that it still works at all, there haven't been any updates to that file for years.  But, cool, it works! 

> Is there a workaround? 

Probably adding an entry to handle the `selectWindow` would be appropriate. But, I can't find support for this command in either the [ruby](https://github.com/SeleniumHQ/selenium/blob/master/ide/plugins/ruby-format/src/content/formats/ruby-wd.js) or [python](https://github.com/SeleniumHQ/selenium/blob/master/ide/plugins/python-format/src/content/formats/python2-wd.js) equivalents of our ide-plugin, so that's kind of odd.

> Are there plans to support selectWindow in the future?

I'm pretty curious about this (although since neither the python nor ruby analogs have this, it might not be possible for some reason???), but my main priority right now is getting a release out for #271 to support the new Firefox stuff, so I don't have any bandwidth to spare for this at the moment. 

I'd probably start by adding a `selectWindow` command to the prototype and then log out its arguments and see if they're anything useful. Assuming that `selectWindow` is getting called against `Driver`, something like:

```js
WDAPI.Driver.prototype.selectWindow = function() {
    return console.log(arguments);
};
```

might be useful? Oh, actually - do Firefox plugins log out to the same console that you'd see on the page? It might be more useful to `JSON.stringify` the arguments and just return them into the perl script instead of console.log...

**Comment by teodesian** [comment]
Yet another "unofficial" command like the one to send files to the server.  Not shocked, and I have no problem with such a function being added to the module.  That said, it may be some time until I can look into this.

**Comment by teodesian** [comment]
not supported in WC3 webdriver, not getting done
