### ISSUE TITLE
"page load" timeout doesn't work

### ISSUE THREAD

**Issue by toreau** [teodesian/Selenium-Remote-Driver#290]
Given this code:

``` perl
my $firefox = Selenium::Firefox->new(
    remote_server_addr => '127.0.0.1',
    port               => 9090,
);

$firefox->set_timeout( 'page load', 10_000 );

$firefox->get( 'http://www.someurl.com/fubar' );
my $dom = Mojo::DOM->new( $self->firefox->get_page_source );
```

However, for certain sites that keeps on loading something in the background, this code never times out. I've even tried using `$SIG{ALRM}` without any luck.

**Comment by gempesaw** [comment]
My suspicion is that this is an issue with how we're incorrectly handling exceptions for Selenium::Firefox (and Selenium::Chrome), instead of an issue with `page load` timeout. That is, I think this snippet would work with Selenium::Remote::Driver.

Not that that necessarily helps you any, just musing.

**Comment by Qarj** [comment]
I'm using Chrome with Selenium::Remote::Driver and set_timeout is definitely working.

**Comment by gerhardj** [comment]
This and #293 should be fixed by the referenced commit above.

Background is, that geckodriver expects a little different format, that is `{"<type>": "<milliseconds>"}`
instead of the current `{"type":"<type", "ms": "<milliseconds>"}`

so for example:

    {"page load": "10 000"}
