### ISSUE TITLE
execute_async_scriptI() times out when run for an IFRAME

### ISSUE THREAD

**Issue by zenlark** [teodesian/Selenium-Remote-Driver#337]
If a page has more than one frame and I switch to one of them, even the simplest of JS scripts run using execute_async_script() time out. At the same time execute_script() works fine. This has been detected while using Selenium::PhantomJS on a URL: https://www.schwab.com/public/schwab/nn/login/login.html&lang=en with frame id: 'loginIframe'. 
Linux Mint 18 x64, Perl 5.22.1, PhantomJS 2.2.1 (downloaded from their site).

```perl
#! perl -w 
use strict;
use warnings;
use feature 'say';
use Data::Dumper qw(Dumper);
use Selenium::PhantomJS;
use Selenium::Remote::WebElement;
use Selenium::Waiter;
use Try::Tiny;

my $driver = Selenium::PhantomJS->new;

#say Dumper $driver->status;

$driver->get( "https://www.schwab.com/public/schwab/nn/login/login.html&lang=en" );

wait_until {
	say "Waiting for login form...";
	my @inputs = $driver->find_elements("//iframe");
	my @has_login_id = grep { $_->get_attribute('id') eq 'loginIframe' } @inputs; 
} timeout => 10, interval => 1 ;

###############################################
# UNCOMMENT THE LINE BELOW TO SEE THE ISSUE
#
#$driver->switch_to_frame('loginIframe');
#
###############################################

my $login_input; 
try {
$login_input = $driver->find_element( "//input[\@id='LoginId']" );
say "Login ID class: @{[$login_input->get_attribute('class')]}";

say "Current URL: ".$driver->get_current_url;
} catch {};

if (1){
	say "Running sync JS...";
	my $result = $driver->execute_script( q{ 
		var result = '';
		var inputs = document.getElementsByTagName('input') || [];
		for( var i=0; i<inputs.length; ++i){
			result += "id " + i + ": <" + inputs[i].getAttribute('id') + '>,';
		}
		return 'inputs: '+result;
	}, "hello");

	say "Result from sync JS: --$result-- ";
};

if(1) {
	say "Running async JS...";
	my $result = $driver->execute_async_script( q{ 
		var arg = arguments[0];
		var cb = arguments[1];
		cb(arg);
	}, "hello");

	say "Result from async JS: --$result-- ";
} ;

$driver->shutdown_binary;
```

**Comment by teodesian** [comment]
The script never returns because the listener it defines is on the iframe, but new events can't be defined on iFrames due to XSS risk (this is blocked in newer browsers).  iFrames are basically read-only at this point to frustrate phishing.

It used to be that you would have to define a secondary listener within your async script that listens for events in the frame, and then runs the alert cb, because selenium never defined the waiters on the proper frame anyways.

Summary: This probably won't work no matter what you do.  I think you can still do reading of page state, but can't fire events, etc. on the page in the iframe, which is likely what you have to do to make this work.
