### ISSUE TITLE
set_local_storage_item()?

### ISSUE THREAD

**Issue by hornschorsch** [teodesian/Selenium-Remote-Driver#342]
Hello,

are there plans to make a function or method set_local_storage_item(), according to get_local_storage_item() which already exists?

Kind Regards,
Georg

**Comment by teodesian** [comment]
Seems to be supported by latest selenium:

https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/remote/server/handler/html5/SetLocalStorageItem.html
https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/remote/server/handler/html5/RemoveLocalStorageItem.html

I'll look at adding these methods (and possibly a few other local storage methods) tonight.

**Comment by teodesian** [comment]
Well, this was a fun journey to actually figure out what's supported by selenium, because the spec is 1000% useless.  Tracking it down in the source was the only way to go, and it seems there are about 4 different things to look at to figure out what verb to use when doing S::R::D_execute_command(), and then what args I actually have to pass.  I really should update the wiki for budding new authors who want to update S::R::D to support $COMMAND in the future.

I should also probably audit and just throw in the darn kitchen sink of everything they currently have.

**Comment by hornschorsch** [comment]
Hello,

thanks for your efforts. Is there any place to discuss S:R:D-relatetd issues? Is https://groups.google.com/forum/#!forum/selenium-remote-driver
still active?

I have a special problem with a website that stores data in the local storage of the browser and reuses that data the next time you visit the site. But because selenium and/or geckodriver make a copy of the firefox profile for each run and delete that copy on exit, the data gets lost. My first approach was to retrieve the data with get_local_storage_item at the end of a testrun and store it separately, then inject it again with set_local_storage_item at the beginning of the next tstrun before opening the webpage.

I emulated set_local_storage_item with `execute_script("window.localStorage.setItem('...` but this does not work because local storage is domain based and you can not set an item before you have loaded a page...

Is there a possibility to fetch the name of the temporary profile folder (something linke /tmp/rust_mozprofile...)? Then i could copy the storage-subfolder of the temp profile back to the original profile, so that the stored data gets used the next time.

And please forgive me if this is the wrong place to discuss such things. But i found more than one who had the same problem but no real solution.

**Comment by teodesian** [comment]
Given a lack of any real other place to discuss these things, I'm OK with this for now.  I may start a mailing list at some point soon.

As to fetching the profile data from the remote server, that could get tricky.  I don't think there's any specific method to get the folder you want...but I suspect it's identified by the session ID, which you can get.  So long as we can figure out the base dir used to store the temporary profiles you hopefully can get something like this going (supposing you can SSH into the remote server with Net::OpenSSH, etc).

I'm not sure I'll have time for a research project like that this week.

**Comment by hornschorsch** [comment]
The temporary profile_folder is named like /tmp/rust_mozprofile.IM7cigHHyPfx
Sorry for the stupid question, but how can i get the session ID?

ssh is not neccessary because everything runs on the same machine.

**Comment by Qarj** [comment]
I get the session id as follows, if we are talking about the same thing:

```
    my $_session_info =  eval { Data::Dumper::Dumper( $driver->get_capabilities() ); };
    $_session_info =~ m/'webdriver.remote.sessionid' => '([^']*)'/; #'
    my $_session_id;
    if ($1) {$_session_id = $1};
```

**Comment by teodesian** [comment]
Hmm, if it's named like that it looks like it's just using a unique id rather than identifying by session (they're probably just using a capability like File::Temp, but in Java).

To be able to do that while on your local system you'd have to watch the tmp folder and look for what was newly created after you instantiate S::R::D.  That shouldn't be a problem whether the system is remote or local I imagine.

That said, it's probably not something I'd want to implement in S::R::D; but maybe in a utility library we might bundle.  In any case, I'd consider it low priority given set_local_storage_item should resolve your problem, right?

**Comment by teodesian** [comment]
Added a wiki entry on how to do this in the future when I forget:

https://github.com/teodesian/Selenium-Remote-Driver/wiki/How-to-add-new-methods-from-the-WebDriver-Spec

Anyways, testing this is gonna be kind of a PITA, given I can't just sort of dope out a new mock recording and plop it in there -- I've gotta do the "real thing".  And getting that set up will probably be a weekend project.

**Comment by hornschorsch** [comment]
webdriver.remote.sessionid is the name of the tmp folder that selenium creates. geckodriver then creates another copy of the profile folder... Watching the /tmp folder is potentially unsave because there is probably more than one instance runing on the same machine, but it could do the trick for now.

Im not yet sure if set_local_storage_item resolves my problem. I just updated to S:R:D 1.20 and selenium server 3.7.1 and now i get another error (see separate issue).

**Comment by teodesian** [comment]
No real method in WC3, this would have to be a JS shim

**Comment by teodesian** [comment]
Closing this, as the reality is selenium is just inadequate for doing this.

Selenium as a project has basically failed and been leapfrogged by Puppeteer .

**Comment by hornschorsch** [comment]
Hello, and sorry for posting into a closed issue, but are you going to stop the support for S:R:D?

I dont need the set_local_storage_item() anymore and Selenium is working fine for me...
