### ISSUE TITLE
Selenium::Remote::Driver->new( profile => 'path/to/file/' ) not working

### ISSUE THREAD

**Issue by hornschorsch** [teodesian/Selenium-Remote-Driver#365]
Hi,

as discussed here: https://groups.google.com/forum/#!topic/selenium-remote-driver/u_yAGsdxuNs the question is how to start firefox with a given profile folder. The suggested solution, to use 

Selenium::Remote::Driver->new( profile => 'path/to/file/' )

with Version 1.21 does not work. Firefox is started as usual with a temporary profile folder. From the selenium logfile:

1517407718804   mozrunner::runner       INFO    Running command: "/usr/bin/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.kTC7WyiucIZg"
1517407719976   Marionette      INFO    Enabled via --marionette
1517407723130   Marionette      INFO    Listening on port 49796

$driver = Selenium::Remote::Driver->new(
            extra_capabilities => {
                'acceptInsecureCerts' => JSON::true,
                'moz:firefoxOptions' => {
                    args => [ "-profile", "/home/horn/.mozilla/firefox/8bkxxzc6.lisi" ],
                },
            });

does start the browser with the profile folder:

1517407792560   mozrunner::runner       INFO    Running command: "/usr/bin/firefox" "-marionette" "-profile" "/home/horn/.mozilla/firefox/8bkxxzc6.lisi"
1517407792808   Marionette      INFO    Enabled via --marionette
1517407793430   Marionette      INFO    Listening on port 2828

but then it fails to connect to marionette: The portnumber is always 2828 in this case while it varies every time when i omit -profile ...

Is this a bug in geckodriver?

**Comment by hornschorsch** [comment]
According to https://github.com/mozilla/geckodriver/issues/1058 it is a bug in geckodriver. But how is Selenium::Remote::Driver->new( profile => 'path/to/file/' ); supposed to work?

**Comment by teodesian** [comment]
I noticed there was a bug in this in #363 .  I fixed this, but noticed that I had to work around a bug in geckodriver that makes it prefer old-style capabilities like so:

`$Selenium::Remote::Driver::FORCE_WD3 = 1;`
`Selenium::Remote::Driver->new(...);`

Basically geckodriver *should* try and use the new caps that are passed correctly, but it still prefers the old JSONWire style caps if both are passed.  As such, you need to set the above variable to *only* pass the new style caps if you want the calling convention similar to the above to work.

Also, the profile option expects either a Selenium::Firefox::Profile object, or a base64'd zip file of a profile directory, so the path to a directory would just not work.

See the Module's POD in the 'Firefox Notes' subheading of 'COMPATIBILITY':
https://metacpan.org/pod/Selenium::Remote::Driver#Firefox-Notes
And upgrade to 1.23 as soon as is convenient, since #363 should be fixed there.

Otherwise, if you want to pass a directory rather than using a Selenium::Firefox::Profile and the firefox_profile key in the constructor, do the following:

`Selenium::Remote::Driver->new( extra_capabilities => { profile => '/path/to/profile/dir/'}`);`

And it should translate that correctly into moz:FirefoxOptions like the driver expects.  If you'd like me to make the firefox_profile option accept a directory, I'd accept that as a feature request.

**Comment by hornschorsch** [comment]
> Also, the profile option expects either a Selenium::Firefox::Profile object, or a base64'd zip file of a 
> profile directory, so the path to a directory would just not work.

> If you'd like me to make the firefox_profile option accept a directory, I'd accept that as a feature request.

Would that create a base64 encoded zipfile from that dir and pass it into selenium with the profile option? That would not solve my problem, i want firefox to use the same profile directory on every run, so that cookies, local storage items etc. are reused. So i'm afraid i have to wait for the geckodriver bug to be fixed...

**Comment by teodesian** [comment]
Well, you can pass things the way you were by doing 

`$driver = Selenium::Remote::Driver->new(
extra_capabilities => {
'acceptInsecureCerts' => JSON::true,
'moz:firefoxOptions' => {
args => [ "-profile", "/home/horn/.mozilla/firefox/8bkxxzc6.lisi" ],
},
});`

Or, alternatively I can write some code to accept a directory as firefox_options.  It sounds like the latter is what you are interested in, so I'll go with that.  Should make life easier all around.

That said, I can't help you with the geckodriver bug about marionette, you will have to wait for that to clear.

**Comment by teodesian** [comment]
This should be fixed in #396
