### ISSUE TITLE
why does parse_response croak on errors?

### ISSUE THREAD

**Issue by hornschorsch** [teodesian/Selenium-Remote-Driver#369]
Hi,

using S:R:D 1.22 i was testing a site that was not available for a while. My testscript croaked every time with the following message:

> Error while executing command: unknown error: Reached error page: about:neterror?e=netTimeout&u=https%3A//desa-integration.privatevault.ch/&c=UTF-8&f=regular&d=Der%20Server%20unter%20desa-integration.privatevault.ch%20braucht%20zu%20lange%2C%20um%20eine%20Antwort%20zu%20senden. at /usr/local/share/perl5/Selenium/Remote/Driver.pm line 388.

and left a lot of firefox and geckodriver processes behind. I replaced the "croak $msg;" in line 210 of file Spec.pm with "print $msg;" and this works. So why does it originally croak here?

For example the following script fails to load https://bla.fasel.com/ but then at least continues to test the second site and closes the session instead of leaving open sessions behind:

```
$driver = Selenium::Remote::Driver->new();
$driver->debug_on();
$driver->get("https://bla.fasel.com/");
$driver->get("https://manitu.koblenz-net.de/");
print $driver->get_page_source();
$driver->close();
```
```
Prepping get
Executing get
REQ: POST, http://localhost:4444/wd/hub/session/627d9f0c-ee05-4065-937a-97ebcddb6abd/url, {"url":"https://bla.fasel.com/"}
RES: {"value":{"error":"unknown error","message":"Reached error page: about:neterror?e=dnsNotFound&u=https%3A//bla.fasel.com/&c=UTF-8&f=regular&d=Der%20Server%20unter%20bla.fasel.com%20konnte%20nicht%20gefunden%20werden.","stacktrace":"WebDriverError@chrome://marionette/content/error.js:222:5\nUnknownError@chrome://marionette/content/error.js:500:5\nhandleEvent@chrome://marionette/content/listener.js:245:21\n"}}

Error while executing command: unknown error: Reached error page: about:neterror?e=dnsNotFound&u=https%3A//bla.fasel.com/&c=UTF-8&f=regular&d=Der%20Server%20unter%20bla.fasel.com%20konnte%20nicht%20gefunden%20werden.
Prepping get
Executing get
REQ: POST, http://localhost:4444/wd/hub/session/627d9f0c-ee05-4065-937a-97ebcddb6abd/url, {"url":"https://manitu.koblenz-net.de/"}
RES: {"value": {}}

Prepping getPageSource
Executing getPageSource
REQ: GET, http://localhost:4444/wd/hub/session/627d9f0c-ee05-4065-937a-97ebcddb6abd/source, {}
RES: {"value":"<html><head></head><body></body></html>"}

<html><head></head><body></body></html>Prepping close
Executing close
REQ: DELETE, http://localhost:4444/wd/hub/session/627d9f0c-ee05-4065-937a-97ebcddb6abd/window, {}
RES: {"value": []}
```

**Comment by teodesian** [comment]
It's always croaked in it's predecessor module Selenium::Remote::Commands, see https://metacpan.org/source/TEODESIAN/Selenium-Remote-Driver-1.24/lib/Selenium/Remote/Commands.pm#L504. The assumption is that you want your test to fail when you can't access a resource.  That said, perhaps the assumption needs re-visiting?

I think the reason it's leaving sessions behind is because it's not running the destructor for some reason, which will probably have to be investigated.  Is the script you posted above sufficient for reproducing the problem if I say, edited /etc/hosts to blackhole the first site?

**Comment by hornschorsch** [comment]
Hi,

"We have always done it that way" is probably not the best argument. ;-)

I personally prefer functions or methods which return an arror code or an error message if something goes wrong, then i can react in my application and croak myself if i believe the error is so bad.

In my case i have a script that tests various websites and it is not neccessary to stop the whole testrun just because one site failed.

The DEMOLISH subroutine is called but returns because $in_global_destruction is set. I removed that test but then an other error occurs:

(in cleanup) Can't call method "get_params" on an undefined value at /usr/local/share/perl5/Selenium/Remote/Driver.pm line 367 during global destruction.
 at /usr/local/share/perl5/Selenium/Remote/Driver.pm line 345.

**Comment by teodesian** [comment]
yeah, the whole destructors not running reliably in global destruction is pretty hard to get around.  I generally prefer END blocks rather than destroy methods because of this in my own code.  It would take a pretty significant re-design of how things work to not have that be a problem, so I'm not likely to do anything about it.

Anyways, I'm also partial to non-fatal failures; that said this would be a pretty significant (breaking) behavior change for the module.  It's pretty much been klingon programming from the start (better to die than return() in failure)... so there's a lot of code out there relying on eval {} ing this stuff.

I'd probably want that to be a global toggle like a $driver->croak_on_failure(0), rather than just outright changing it as such, and leaving the default behavior alone.

I'll mark this as a feature request, but it will be low-priority.

**Comment by teodesian** [comment]
this has been a thing long enough I'm not gonna change it
