### ISSUE TITLE
Documentation indicates chromeOptions does not work?

### ISSUE THREAD

**Issue by rlauer6** [teodesian/Selenium-Remote-Driver#384]
...odd because the only way I could get a headless __Amazon Linux/google chrome/selenium server__ stack running was thusly:

```
my $chrome_options =  {
                       args => [
                                'no-sandbox',
                                'binary=/usr/bin/google-chrome-stable',
                                'headless'
                               ]
                      };

my $driver = new Selenium::Remote::Driver(
                                          browser_name       => 'chrome',
                                          extra_capabilities => { chromeOptions => $chrome_options },
                                          binary             => '/home/ec2-user/chromedriver'
                                         );
```

Is there a different (better) way I should be doing this or what am I missing or is the newer `chromedriver` behaving?

My setup:

* **chromedriver:**  _ChromeDriver 2.38.552522_ (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb)_
* **selenium server:** _Selenium build info: version: '3.12.0', revision: '7c6e0b3'_
* **chrome:** _Google Chrome 66.0.3359.181_

**Comment by teodesian** [comment]
Extra caps for chromeOptions don't work in WC3 mode, which is why I forced chromedriver usage into JSONWire mode:

Read the entire section 'chrome notes' here:
https://metacpan.org/pod/Selenium::Remote::Driver#Chrome-Notes

This is why your code works.  Because I disabled WC3 method usage in chromedriver with a hammer until they get their act together.
