### ISSUE TITLE
S::R::D fails to get class attribute on Firefox

### ISSUE THREAD

**Issue by ylavoie** [teodesian/Selenium-Remote-Driver#429]
Using FF v66, WebElement uses get_property instead of get_attribute for a class and returns an empty value
 {
    command   "getElementProperty",
    id        "24851d23-cb09-475b-ac8c-5db2604254aa",
    name      "class"
} at /home/circleci/perl5/perlbrew/perls/perl-5.28.0/lib/site_perl/5.28.0/Selenium/Remote/WebElement.pm line 280.

**Comment by teodesian** [comment]
Forgive the tardy reply.

Is this more confusion over get_attribute returning property value?  I've already gone over this in several issues -- this is done deliberately because the old JSONWire method returned the *property* instead of the attribute, *despite it's name*.  I have to be backwards compatible to not break old tests.

You can pass a flag to make it actually fetch the attribute instead, it's right there in the documentation.

**Comment by teodesian** [comment]
no input in a year, closing
