### ISSUE TITLE
Without Standalone Server - Any chance of getting a HTMLUnit class?

### ISSUE THREAD

**Issue by inpbox** [teodesian/Selenium-Remote-Driver#447]
Hi,

> If you'd like additional browsers besides these, give us a holler

Would it be possible to implement a new Class (like Selenium::Chrome etc) based on the HTMLUnit-driver:
* [https://github.com/SeleniumHQ/htmlunit-driver](https://github.com/SeleniumHQ/htmlunit-driver)

**Comment by teodesian** [comment]
As far as I can tell htmlunit-driver would need to be baked into the selenium server JAR to work
In which case you may as well just pass it as a browser to the normal S::R::D constructor.

It sounds like their workflow is centered around java;  The lack of support for WD these days in anything else is why I've primarily switched to using node.js puppeteer and https://metacpan.org/pod/Chrome::DevToolsProtocol directly instead of selenium lately.  The latter certainly is nicer than dealing with chromedriver maintainers breaking something nonstop.

A drop in replacement for SRD which doesn't have to use the selenium at all would be wonderful, but I don't have the time for it at  the moment.

**Comment by teodesian** [comment]
this will never happen as a part of this module.
