### ISSUE TITLE
$driver->get() hangs "for ever"

### ISSUE THREAD

**Issue by hornschorsch** [teodesian/Selenium-Remote-Driver#490]
Hello, i am testing an application whose startpage sometimes fails to load completely, that means the page itself is displayed already but the browser seems to still be loading and the smal bullet is moving to and fro above in the browser tab. If that happens $driver->get() will only return after 300 Seconds, when the firefox browser finally produces a timeout, while my script usually times out in 30 seconds after clicking a link or submitting a form in the application.

I tried to find a possibility to decrease the timeout in firefox, there are postings on stackoverflow or superuser.com on how to do this but it doesnt work. I believe the parameters in about:config have been removed.

Is it possible to pass a timout to $driver->get() or does anyone have another idea on how to fix this?

**Comment by teodesian** [comment]
$driver->set_timeout('page load',30000);

$driver->set_timeout('implicit',30000);

 

If that doesn’t do the trick, it’s likely there’s some dopey javascript thing going on, and you’ll have to do:

 

$driver->set_timeout('script',30000);

$driver->set_async_script_timeout(30000);

 

If none of these work, then you are SOL.

 

By contrast, if you use playwright you can wait on any throwable event in javascript.  Far better model than what selenium does, which is try to guess what any given action will fire and wait on that.

 

In the past I have had to deal with nonsense like this.  I’d set the timeouts  to 1ms, eval get() and just poll until what I wanted was on the page.

I would then inform the frontend dev who abused the browser into acting like this how they could actually play nice instead of torturing the browser into compliance.

 

GSB

 

PS:

 

UI Devs of course never listen.  This is why we have nonsense like web components which randomize their selectors everytime they are used (because UI devs don’t understand CSS), and are thus impossible to use selenium reliably with.

Playwright tortures these values directly from the browser’s memory, while the selenium standard remains ossified and unmoving save in the direction of removing features.

Your only option with selenium is to use CDP, which begs the question why anyone uses selenium at all other than as a legacy testsuite.

 

From: Georg Horn ***@***.***> 
Sent: Tuesday, February 20, 2024 8:52 AM
To: teodesian/Selenium-Remote-Driver ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [teodesian/Selenium-Remote-Driver] $driver->get() hangs "for ever" (Issue #490)

 

Hello, i am testing an application whose startpage sometimes fails to load completely, that means the page itself is displayed already but the browser seems to still be loading and the smal bullet is moving to and fro above in the browser tab. If that happens $driver->get() will only return after 300 Seconds, when the firefox browser finally produces a timeout, while my script usually times out in 30 seconds after clicking a link or submitting a form in the application.

I tried to find a possibility to decrease the timeout in firefox, there are postings on stackoverflow or superuser.com on how to do this but it doesnt work. I believe the parameters in about:config have been removed.

Is it possible to pass a timout to $driver->get() or does anyone have another idea on how to fix this?

**Comment by hornschorsch** [comment]
Hi, thanks for your great reply, it seems to work!

Another idea i had shortly after writing my post would be: Load a local page that is always available and that contains a link to the startpage of the actual application and then click() on that link. The click() returns after a second or so and you can then wait for the page to load and timeout when you want.

And yes, i should take a look into playwright...

**Comment by teodesian** [comment]
Cool, glad to hear it.  Closing issue.
